// <auto-generated />
namespace MVCPracticeProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changPriceFromFloatToDouble : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changPriceFromFloatToDouble));
        
        string IMigrationMetadata.Id
        {
            get { return "201704171015312_changPriceFromFloatToDouble"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
